obj-m += snd-hda-codec-ca0132.o
snd-hda-codec-ca0132-y := ca0132.o ae5_direct_route_cycle.o ae5_path_cycle.o ae5_clock_cycle.o ae5_route_plan.o ae5_route_capture.o ae5_dac_volume.o
ccflags-y += -I$(src) -Werror
