# The native AE-5 Direct output is managed by the driver service.
monitor.alsa.rules = [
 { matches = [ { device.name = "alsa_card.pci-@PCI@" } ]
   actions = { update-props = { device.disabled = true } }
 }
]
